# Generated by Django 6.1.1 on 2026-09-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_aliment', models.CharField(max_length=120, verbose_name='Type d’aliment')),
                ('quantite_kg', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Quantité (kg)')),
                ('frequence', models.CharField(max_length=80, verbose_name='Fréquence')),
                ('date_alimentation', models.DateField(verbose_name='Date alimentation')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Alimentation',
                'verbose_name_plural': 'Alimentations',
            },
        ),
    ]
