# Generated by Django 6.1.1 on 2026-09-13 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimentation', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequenceAlimentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, unique=True, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Fréquence d'alimentation",
                'verbose_name_plural': "Fréquences d'alimentation",
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='TypeAliment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, unique=True, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Type d'aliment",
                'verbose_name_plural': "Types d'aliment",
                'ordering': ['nom'],
            },
        ),
        migrations.AlterModelOptions(
            name='alimentation',
            options={'ordering': ['-date_alimentation'], 'verbose_name': 'Alimentation', 'verbose_name_plural': 'Alimentations'},
        ),
        migrations.AddField(
            model_name='alimentation',
            name='note',
            field=models.TextField(blank=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='alimentation',
            name='frequence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alimentations', to='alimentation.frequencealimentation', verbose_name='Fréquence'),
        ),
        migrations.AlterField(
            model_name='alimentation',
            name='type_aliment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alimentations', to='alimentation.typealiment', verbose_name="Type d'aliment"),
        ),
    ]
