# Generated by Django 6.1.1 on 2026-09-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix')),
                ('duree_mois', models.IntegerField(default=1, verbose_name='Durée en mois')),
                ('nb_fermes_max', models.IntegerField(default=1, verbose_name='Nombre maximum de fermes')),
                ('nb_animaux_max', models.IntegerField(default=50, verbose_name='Nombre maximum d’animaux')),
                ('acces_ia', models.BooleanField(default=False, verbose_name='Accès IA')),
                ('acces_support', models.BooleanField(default=False, verbose_name='Accès support')),
                ('acces_analyses', models.BooleanField(default=False, verbose_name='Accès analyses')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
            },
        ),
    ]
