# Generated by Django 6.1.1 on 2026-09-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(verbose_name='Date début')),
                ('date_prevue', models.DateField(verbose_name='Date prévue')),
                ('duree_jours', models.PositiveIntegerField(default=0, verbose_name='Durée (jours)')),
                ('statut', models.CharField(default='active', max_length=60, verbose_name='Statut')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Gestation',
                'verbose_name_plural': 'Gestations',
            },
        ),
    ]
