# Generated by Django 6.1.1 on 2026-09-14 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestation', '0002_initial'),
        ('moncheptel', '0003_remove_animal_statut_animal_etat_sante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestation',
            name='date_mise_bas_reelle',
            field=models.DateField(blank=True, null=True, verbose_name='Date mise bas réelle'),
        ),
        migrations.AddField(
            model_name='gestation',
            name='nombre_naissances',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de naissances'),
        ),
        migrations.AddField(
            model_name='gestation',
            name='pere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gestations_comme_pere', to='moncheptel.animal', verbose_name='Mâle reproducteur'),
        ),
        migrations.AlterField(
            model_name='gestation',
            name='date_debut',
            field=models.DateField(verbose_name='Date de saillie'),
        ),
        migrations.AlterField(
            model_name='gestation',
            name='duree_jours',
            field=models.PositiveIntegerField(default=0, verbose_name='Durée estimée (jours)'),
        ),
    ]
