# Generated by Django 6.1.1 on 2026-09-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueEvenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_evenement', models.CharField(max_length=80, verbose_name='Type d’événement')),
                ('titre', models.CharField(max_length=150, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_evenement', models.DateTimeField(verbose_name='Date événement')),
                ('source_ia', models.BooleanField(default=False, verbose_name='Source IA')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Historique événement',
                'verbose_name_plural': 'Historique événements',
            },
        ),
    ]
