# Generated by Django 6.1.1 on 2026-09-13 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fermes', '0001_initial'),
        ('moncheptel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuiviSante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(verbose_name='Date début')),
                ('date_prochaine_consultation', models.DateField(verbose_name='Date prochaine consultation')),
                ('statut', models.CharField(max_length=80, verbose_name='Statut')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sante_suivis', to='moncheptel.animal', verbose_name='Animal')),
                ('ferme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sante_suivis', to='fermes.ferme', verbose_name='Ferme')),
            ],
            options={
                'verbose_name': 'Suivi santé',
                'verbose_name_plural': 'Suivis santé',
            },
        ),
    ]
