# Generated by Django 6.1.1 on 2026-09-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suivisante',
            name='date_debut',
            field=models.DateField(blank=True, null=True, verbose_name='Date début'),
        ),
        migrations.AlterField(
            model_name='suivisante',
            name='date_prochaine_consultation',
            field=models.DateField(blank=True, null=True, verbose_name='Date prochaine consultation'),
        ),
    ]
