# Generated by Django 6.1.1 on 2026-09-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante', '0002_alter_suivisante_date_debut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suivisante',
            name='frequence_cardiaque',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Fréquence cardiaque (bpm)'),
        ),
        migrations.AddField(
            model_name='suivisante',
            name='poids_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Poids actuel (kg)'),
        ),
        migrations.AddField(
            model_name='suivisante',
            name='temperature_celsius',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Température (°C)'),
        ),
    ]
