# Generated by Django 6.1.1 on 2026-09-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante', '0003_suivisante_frequence_cardiaque_suivisante_poids_kg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suivisante',
            name='date_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin / guérison'),
        ),
    ]
