# Generated by Django 6.1.1 on 2026-09-30 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fermes', '0001_initial'),
        ('moncheptel', '0004_animal_photo'),
        ('sante', '0005_realigner_etat_animaux'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('veterinaire', models.CharField(blank=True, max_length=150)),
                ('date_prescription', models.DateField()),
                ('medicaments', models.TextField()),
                ('instructions', models.TextField(blank=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='ordonnances/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordonnances', to='moncheptel.animal')),
                ('ferme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordonnances', to='fermes.ferme')),
                ('suivi_sante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordonnances', to='sante.suivisante')),
            ],
            options={
                'verbose_name': 'Ordonnance',
                'verbose_name_plural': 'Ordonnances',
                'ordering': ['-date_prescription', '-id'],
            },
        ),
    ]
