# Generated by Django 6.1.1 on 2026-10-09 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante', '0006_ordonnance'),
    ]

    operations = [
        migrations.CreateModel(
            name='RappelOrdonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.TextField()),
                ('date_prochaine_prise', models.DateTimeField()),
                ('intervalle_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('dernier_rappel', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('ordonnance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rappels', to='sante.ordonnance')),
            ],
            options={
                'verbose_name': 'Rappel d’ordonnance',
                'verbose_name_plural': 'Rappels d’ordonnance',
                'indexes': [models.Index(fields=['actif', 'date_prochaine_prise'], name='sante_rappe_actif_8e5993_idx')],
            },
        ),
    ]
