# Generated by Django 6.1.1 on 2026-10-09 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante', '0007_rappelordonnance'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraitementOrdonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicament', models.CharField(max_length=300)),
                ('posologie', models.TextField()),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('ordonnance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traitements', to='sante.ordonnance')),
            ],
            options={
                'verbose_name': 'Médicament prescrit',
                'verbose_name_plural': 'Médicaments prescrits',
            },
        ),
        migrations.AddField(
            model_name='rappelordonnance',
            name='traitement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rappels', to='sante.traitementordonnance'),
        ),
    ]
