# Generated by Django 6.1.1 on 2026-09-13 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fermes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=120, verbose_name='Nom')),
                ('numero_identification', models.CharField(max_length=80, unique=True, verbose_name='Numéro d’identification')),
                ('espece', models.CharField(max_length=80, verbose_name='Espèce')),
                ('race', models.CharField(blank=True, max_length=80, verbose_name='Race')),
                ('sexe', models.CharField(choices=[('male', 'Mâle'), ('femelle', 'Femelle')], default='femelle', max_length=20, verbose_name='Sexe')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('date_arrivee', models.DateField(blank=True, null=True, verbose_name='Date d’arrivée')),
                ('date_depart', models.DateField(blank=True, null=True, verbose_name='Date de départ')),
                ('poids_naissance', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Poids naissance (kg)')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('vendu', 'Vendu'), ('mort', 'Mort'), ('malade', 'Malade'), ('en_traitement', 'En traitement'), ('gestation', 'Gestation')], default='actif', max_length=30, verbose_name='Statut')),
                ('couleur', models.CharField(blank=True, max_length=80, verbose_name='Couleur')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('ferme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animaux', to='fermes.ferme', verbose_name='Ferme')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animaux',
            },
        ),
    ]
