# Generated by Django 6.1.1 on 2026-09-13 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moncheptel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['numero_identification'], 'verbose_name': 'Animal', 'verbose_name_plural': 'Animaux'},
        ),
        migrations.AlterField(
            model_name='animal',
            name='date_arrivee',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'arrivée"),
        ),
        migrations.AlterField(
            model_name='animal',
            name='espece',
            field=models.CharField(choices=[('bovin', 'Bovin'), ('ovin', 'Ovin'), ('caprin', 'Caprin'), ('porcin', 'Porcin')], max_length=20, verbose_name='Espèce'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='numero_identification',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name="Numéro d'identification"),
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('espece', models.CharField(choices=[('bovin', 'Bovin'), ('ovin', 'Ovin'), ('caprin', 'Caprin'), ('porcin', 'Porcin')], max_length=20, verbose_name='Espèce')),
                ('nom', models.CharField(max_length=120, verbose_name='Nom de la race')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Race',
                'verbose_name_plural': 'Races',
                'ordering': ('espece', 'nom'),
                'unique_together': {('espece', 'nom')},
            },
        ),
        migrations.AlterField(
            model_name='animal',
            name='race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animaux', to='moncheptel.race', verbose_name='Race'),
        ),
    ]
