# Generated by Django 6.1.1 on 2026-09-13 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moncheptel', '0002_alter_animal_options_alter_animal_date_arrivee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='statut',
        ),
        migrations.AddField(
            model_name='animal',
            name='etat_sante',
            field=models.CharField(choices=[('sain', 'Sain'), ('malade', 'Malade'), ('gestation', 'Gestation'), ('en_traitement', 'En traitement')], default='sain', max_length=20, verbose_name='État de santé'),
        ),
        migrations.AddField(
            model_name='animal',
            name='presence',
            field=models.CharField(choices=[('present', 'Présent'), ('vendu', 'Vendu'), ('mort', 'Mort')], default='present', max_length=20, verbose_name='Présence'),
        ),
    ]
