# Generated by Django 6.1.1 on 2026-09-13 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alertes', '0001_initial'),
        ('fermes', '0001_initial'),
        ('moncheptel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerte',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='moncheptel.animal', verbose_name='Animal'),
        ),
        migrations.AddField(
            model_name='alerte',
            name='ferme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='fermes.ferme', verbose_name='Ferme'),
        ),
    ]
