# Generated by Django 6.1.1 on 2026-10-09 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertes', '0002_initial'),
        ('sante', '0007_rappelordonnance'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerte',
            name='rappel_ordonnance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes', to='sante.rappelordonnance', verbose_name='Rappel d’ordonnance'),
        ),
    ]
