# Generated by Django 6.1.1 on 2026-09-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='moyen_paiement',
            field=models.CharField(blank=True, max_length=50, verbose_name='Moyen de paiement'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='paydunya_token',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True, verbose_name='Token PayDunya'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='receipt_url',
            field=models.URLField(blank=True, verbose_name='URL du reçu PayDunya'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='statut',
            field=models.CharField(choices=[('pending', 'pending'), ('active', 'active'), ('expired', 'expired'), ('cancelled', 'cancelled')], default='active', max_length=20, verbose_name='Statut'),
        ),
    ]
