# Generated by Django 6.1.1 on 2026-09-13 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ferme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, verbose_name='Nom de la ferme')),
                ('localisation', models.CharField(blank=True, max_length=150, verbose_name='Localisation')),
                ('superficie', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Superficie (ha)')),
                ('coordonnees_gps', models.CharField(blank=True, max_length=120, verbose_name='Coordonnées GPS')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fermes', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
            ],
            options={
                'verbose_name': 'Ferme',
                'verbose_name_plural': 'Fermes',
            },
        ),
    ]
